# Note: this workflow assumes that your github user name = your Docker Hub user name.
# It will also probably break for GitHub users or repositories with uppercase letters.

name: Automated Build

on:
  workflow_call:
    secrets:
      DOCKER_HUB_TOKEN:
        required: false

env:
  DOCKER_BUILDKIT: 1

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set environment variables
        run: |
          IMAGES=""
          if [ "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo PUSH_TO_DOCKER_HUB=yes >> $GITHUB_ENV
            IMAGES="$IMAGES docker.io/${{ github.repository }}"
          fi
          if true; then
            echo PUSH_TO_GHCR=yes >> $GITHUB_ENV
            IMAGES="$IMAGES ghcr.io/${{ github.repository }}"
          fi
          echo 'IMAGES<<EOF' >> $GITHUB_ENV
          for IMAGE in $IMAGES; do
            echo $IMAGE >> $GITHUB_ENV
          done
          echo 'EOF' >> $GITHUB_ENV

      - 
        uses: actions/checkout@v2

      -
        name: Log into Docker Hub
        if: env.PUSH_TO_DOCKER_HUB
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Log into GitHub Container Registry
        if: env.PUSH_TO_GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        uses: docker/setup-qemu-action@v1

      -
        uses: docker/setup-buildx-action@v1

      -
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.IMAGES }}
