# Note: this workflow assumes that your github user name = your Docker Hub user name.
# It will also probably break for GitHub users or repositories with uppercase letters.

name: Automated Build

on:
  workflow_call:
    secrets:
      DOCKER_HUB_TOKEN:
        required: false

env:
  DOCKER_BUILDKIT: 1

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - 
        uses: actions/checkout@v2

      -
        name: Log into Docker Hub
        #if: secrets.DOCKER_HUB_TOKEN != ''
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      -
        name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        uses: docker/setup-qemu-action@v1

      -
        uses: docker/setup-buildx-action@v1

      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      -
        name: Push to Docker Hub
        #if: secrets.DOCKER_HUB_TOKEN != ''
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ github.repository }}
          push: true

      -
        name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/${{ github.repository }}
          push: true
